# Generated by Django 5.2.3 on 2025-06-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/profiles/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
